[rospy.client][INFO] 2018-12-19 12:53:14,849: init_node, name[/pose_controller], pid[3981]
[xmlrpc][INFO] 2018-12-19 12:53:14,850: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-19 12:53:14,850: Started XML-RPC server [http://NAOrobUSB001:33187/]
[rospy.init][INFO] 2018-12-19 12:53:14,850: ROS Slave URI: [http://NAOrobUSB001:33187/]
[rospy.impl.masterslave][INFO] 2018-12-19 12:53:14,850: _ready: http://NAOrobUSB001:33187/
[rospy.registration][INFO] 2018-12-19 12:53:14,851: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2018-12-19 12:53:14,851: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2018-12-19 12:53:14,951: registered with master
[rospy.rosout][INFO] 2018-12-19 12:53:14,951: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-19 12:53:14,954: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-19 12:53:14,955: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2018-12-19 12:53:14,964: Connecting to NaoQi at 127.0.0.1:9559
[rospy.internal][INFO] 2018-12-19 12:53:15,105: topic[/joint_trajectory/goal] adding connection to [http://NAOrobUSB001:40663/], count 0
[rospy.internal][INFO] 2018-12-19 12:53:15,107: topic[/joint_trajectory/cancel] adding connection to [http://NAOrobUSB001:40663/], count 0
[rospy.internal][INFO] 2018-12-19 12:53:15,172: topic[/joint_trajectory/feedback] adding connection to [/pose_manager], count 0
[rospy.internal][INFO] 2018-12-19 12:53:15,173: topic[/joint_trajectory/result] adding connection to [/pose_manager], count 0
[rospy.internal][INFO] 2018-12-19 12:53:15,177: topic[/joint_trajectory/status] adding connection to [/pose_manager], count 0
[rosout][INFO] 2018-12-19 12:53:15,199: nao_controller initialized
[rosout][INFO] 2018-12-19 12:53:15,200: nao pose_controller running...
[rospy.internal][INFO] 2018-12-19 12:53:15,227: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2018-12-19 12:53:15,464: topic[/joint_stiffness] adding connection to [http://NAOrobUSB001:42075/], count 0
[rospy.core][INFO] 2018-12-19 12:53:39,151: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2018-12-19 12:53:39,156: Unable to initiate TCP/IP socket to NAOrobUSB001:42507 (http://NAOrobUSB001:40663/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-19 12:53:39,157: Unable to initiate TCP/IP socket to NAOrobUSB001:42507 (http://NAOrobUSB001:40663/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2018-12-19 12:53:39,277: Unknown error initiating TCP/IP socket to NAOrobUSB001:41999 (http://NAOrobUSB001:42075/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2018-12-19 12:53:39,277: topic[/joint_stiffness] removing connection to http://NAOrobUSB001:42075/
[rospy.internal][INFO] 2018-12-19 12:53:39,476: topic[/joint_trajectory/status] removing connection to /pose_manager
[rospy.internal][INFO] 2018-12-19 12:53:39,477: topic[/joint_trajectory/result] removing connection to /pose_manager
[rospy.internal][INFO] 2018-12-19 12:53:39,477: topic[/joint_trajectory/feedback] removing connection to /pose_manager
[rospy.internal][WARNING] 2018-12-19 12:53:40,158: Unknown error initiating TCP/IP socket to NAOrobUSB001:42507 (http://NAOrobUSB001:40663/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2018-12-19 12:53:40,158: topic[/joint_trajectory/cancel] removing connection to http://NAOrobUSB001:40663/
[rospy.internal][WARNING] 2018-12-19 12:53:40,158: Unknown error initiating TCP/IP socket to NAOrobUSB001:42507 (http://NAOrobUSB001:40663/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2018-12-19 12:53:40,158: topic[/joint_trajectory/goal] removing connection to http://NAOrobUSB001:40663/
