[rospy.client][INFO] 2018-12-19 14:14:39,767: init_node, name[/pose_controller], pid[31990]
[xmlrpc][INFO] 2018-12-19 14:14:39,767: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2018-12-19 14:14:39,768: Started XML-RPC server [http://NAOrobUSB001:43841/]
[rospy.impl.masterslave][INFO] 2018-12-19 14:14:39,768: _ready: http://NAOrobUSB001:43841/
[xmlrpc][INFO] 2018-12-19 14:14:39,768: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2018-12-19 14:14:39,769: Registering with master node http://localhost:11311
[rospy.init][INFO] 2018-12-19 14:14:39,785: ROS Slave URI: [http://NAOrobUSB001:43841/]
[rospy.init][INFO] 2018-12-19 14:14:39,786: registered with master
[rospy.rosout][INFO] 2018-12-19 14:14:39,786: initializing /rosout core topic
[rospy.rosout][INFO] 2018-12-19 14:14:39,790: connected to core topic /rosout
[rospy.simtime][INFO] 2018-12-19 14:14:39,794: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2018-12-19 14:14:39,804: Connecting to NaoQi at 127.0.0.1:9559
[rospy.internal][INFO] 2018-12-19 14:14:39,868: topic[/joint_trajectory/cancel] adding connection to [http://NAOrobUSB001:33171/], count 0
[rospy.internal][INFO] 2018-12-19 14:14:39,871: topic[/joint_trajectory/goal] adding connection to [http://NAOrobUSB001:33171/], count 0
[rospy.internal][INFO] 2018-12-19 14:14:39,916: topic[/joint_trajectory/feedback] adding connection to [/pose_manager], count 0
[rospy.internal][INFO] 2018-12-19 14:14:39,925: topic[/joint_trajectory/status] adding connection to [/pose_manager], count 0
[rospy.internal][INFO] 2018-12-19 14:14:39,928: topic[/joint_trajectory/result] adding connection to [/pose_manager], count 0
[rosout][INFO] 2018-12-19 14:14:39,981: nao_controller initialized
[rosout][INFO] 2018-12-19 14:14:39,983: nao pose_controller running...
[rospy.internal][INFO] 2018-12-19 14:14:40,010: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2018-12-19 14:14:40,350: topic[/joint_stiffness] adding connection to [http://NAOrobUSB001:39635/], count 0
[rospy.core][INFO] 2018-12-19 14:35:15,842: signal_shutdown [signal-2]
[rospy.internal][ERROR] 2018-12-19 14:35:15,847: Unable to initiate TCP/IP socket to NAOrobUSB001:38859 (http://NAOrobUSB001:33171/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2018-12-19 14:35:15,848: Unable to initiate TCP/IP socket to NAOrobUSB001:38859 (http://NAOrobUSB001:33171/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2018-12-19 14:35:16,067: topic[/joint_trajectory/status] removing connection to /pose_manager
[rospy.internal][INFO] 2018-12-19 14:35:16,340: topic[/joint_trajectory/result] removing connection to /pose_manager
[rospy.internal][INFO] 2018-12-19 14:35:16,340: topic[/joint_trajectory/feedback] removing connection to /pose_manager
[rospy.internal][WARNING] 2018-12-19 14:35:16,849: Unknown error initiating TCP/IP socket to NAOrobUSB001:38859 (http://NAOrobUSB001:33171/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2018-12-19 14:35:16,849: topic[/joint_trajectory/cancel] removing connection to http://NAOrobUSB001:33171/
[rospy.internal][WARNING] 2018-12-19 14:35:16,849: Unknown error initiating TCP/IP socket to NAOrobUSB001:38859 (http://NAOrobUSB001:33171/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2018-12-19 14:35:16,849: topic[/joint_trajectory/goal] removing connection to http://NAOrobUSB001:33171/
