[rospy.client][INFO] 2019-01-17 13:33:59,034: init_node, name[/pepper_robot/pose/pose_controller], pid[15619]
[xmlrpc][INFO] 2019-01-17 13:33:59,034: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2019-01-17 13:33:59,035: Started XML-RPC server [http://NAOrobUSB001:36345/]
[rospy.init][INFO] 2019-01-17 13:33:59,035: ROS Slave URI: [http://NAOrobUSB001:36345/]
[rospy.impl.masterslave][INFO] 2019-01-17 13:33:59,035: _ready: http://NAOrobUSB001:36345/
[rospy.registration][INFO] 2019-01-17 13:33:59,036: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2019-01-17 13:33:59,036: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2019-01-17 13:33:59,135: registered with master
[rospy.rosout][INFO] 2019-01-17 13:33:59,136: initializing /rosout core topic
[rospy.rosout][INFO] 2019-01-17 13:33:59,139: connected to core topic /rosout
[rospy.simtime][INFO] 2019-01-17 13:33:59,141: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rosout][INFO] 2019-01-17 13:33:59,155: Connecting to NaoQi at 192.168.0.20:9559
[rospy.internal][INFO] 2019-01-17 13:34:00,716: topic[/rosout] adding connection to [/rosout], count 0
[rosout][WARNING] 2019-01-17 13:34:00,865: Collection LLeg not found on your robot.
[rosout][WARNING] 2019-01-17 13:34:00,878: Collection RLeg not found on your robot.
[rospy.internal][INFO] 2019-01-17 13:34:01,131: topic[/pepper_robot/pose/joint_trajectory/goal] adding connection to [http://NAOrobUSB001:34595/], count 0
[rospy.internal][INFO] 2019-01-17 13:34:01,132: topic[/pepper_robot/pose/joint_trajectory/cancel] adding connection to [http://NAOrobUSB001:34595/], count 0
[rospy.internal][INFO] 2019-01-17 13:34:01,187: topic[/pepper_robot/pose/joint_trajectory/feedback] adding connection to [/pepper_robot/pose/pose_manager], count 0
[rospy.internal][INFO] 2019-01-17 13:34:01,189: topic[/pepper_robot/pose/joint_trajectory/result] adding connection to [/pepper_robot/pose/pose_manager], count 0
[rospy.internal][INFO] 2019-01-17 13:34:01,190: topic[/pepper_robot/pose/joint_trajectory/status] adding connection to [/pepper_robot/pose/pose_manager], count 0
[rosout][INFO] 2019-01-17 13:34:01,193: nao_controller initialized
[rosout][INFO] 2019-01-17 13:34:01,194: nao pose_controller running...
[rospy.core][INFO] 2019-01-17 13:34:25,018: signal_shutdown [signal-2]
[rosout][INFO] 2019-01-17 13:34:25,018: Stopping pose_controller
[rosout][INFO] 2019-01-17 13:34:25,019: pose_controller stopped
[rospy.internal][INFO] 2019-01-17 13:34:25,032: topic[/pepper_robot/pose/joint_trajectory/result] removing connection to /pepper_robot/pose/pose_manager
[rospy.internal][INFO] 2019-01-17 13:34:25,032: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2019-01-17 13:34:25,032: topic[/pepper_robot/pose/joint_trajectory/feedback] removing connection to /pepper_robot/pose/pose_manager
[rospy.internal][INFO] 2019-01-17 13:34:25,032: topic[/pepper_robot/pose/joint_trajectory/status] removing connection to /pepper_robot/pose/pose_manager
[rospy.internal][INFO] 2019-01-17 13:34:25,032: topic[/pepper_robot/pose/joint_trajectory/cancel] removing connection to http://NAOrobUSB001:34595/
[rospy.internal][INFO] 2019-01-17 13:34:25,033: topic[/pepper_robot/pose/joint_trajectory/goal] removing connection to http://NAOrobUSB001:34595/
[rospy.impl.masterslave][INFO] 2019-01-17 13:34:25,033: signal-2
[rospy.internal][ERROR] 2019-01-17 13:34:25,467: Unable to initiate TCP/IP socket to NAOrobUSB001:45319 (http://NAOrobUSB001:34595/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2019-01-17 13:34:25,467: Unable to initiate TCP/IP socket to NAOrobUSB001:45319 (http://NAOrobUSB001:34595/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 593, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][INFO] 2019-01-17 13:34:25,647: nao pose_controller stopped.
[rospy.core][INFO] 2019-01-17 13:34:25,648: signal_shutdown [atexit]
